CREATE OR REPLACE VIEW vw_powerbi_telecom_model AS
SELECT 
    c.customer_id,
    c.gender,
    c.age,
    c.age_group,
    c.married,
    c.number_of_dependents,
    c.household_size,
    l.city,
    l.zip_code,
    l.latitude,
    l.longitude,
    l.population,
    s.offer,
    s.contract,
    s.payment_method,
    s.paperless_billing,
    s.phone_service,
    s.multiple_lines,
    s.internet_service,
    s.internet_type,
    s.online_security,
    s.online_backup,
    s.device_protection_plan,
    s.premium_tech_support,
    s.streaming_tv,
    s.streaming_movies,
    s.streaming_music,
    s.unlimited_data,
    s.total_addon_services,
    f.tenure_in_months,
    f.tenure_group,
    f.number_of_referrals,
    f.referral_group,
    f.monthly_charge,
    f.monthly_arpu,
    f.total_charges,
    f.total_refunds,
    f.total_extra_data_charges,
    f.total_long_distance_charges,
    f.total_revenue,
    f.customer_status,
    f.churn_category,
    f.churn_reason,
    f.is_churned
FROM fact_churn f
JOIN dim_customer c ON f.customer_id = c.customer_id
JOIN dim_location l ON f.zip_code = l.zip_code
JOIN dim_subscription s ON f.customer_id = s.customer_id;